export const ScreenPaths = {
  splash: "/",
  onboarding1: "/onboarding-1",
  onboarding2: "/onboarding-2",
  loginOrRegister: "/login-or-register",
  register: "/register",
  registerData: "/register_data",
  registerDone: "/register-done",
  login: "/login",
  loginData: "/login-data",
  loginDone: "/login-done",
  forgotPassword: "/forgot-password",
  pokemons: "/pokemons",
  pokemonDetails: "/pokemon-details",
  regions: "/regions",
  favorites: "/favorites",
  account: "/account",
  updateEmail: "/update-email",
  updatePassword: "/update-password",
  updateName: "/update-name",
};
