export const ScreenPaths = {
  splash: "/",
  onboarding1: "/onboarding1",
  onboarding2: "/onboarding2",
  loginOrRegister: "/loginOrRegister",
  register: "/register",
  registerData: "/registerData",
  registerDone: "/registerDone",
  login: "/login",
  loginData: "/loginData",
  loginDone: "/loginDone",
  forgotPassword: "/forgotPassword",
  pokedex: "/pokedex",
  regions: "/regions",
  favorites: "/favorites",
  account: "/account",
};
