export const Pages = {
  splash: "/",
  onboarding1: "/onboarding1",
  onboarding2: "/onboarding2",
  loginOrRegister: "/loginOrRegister",
  register: "/register",
  registerEmail: "/registerEmail",
  registerPassword: "/registerPassword",
  registerName: "/registerName",
  registerDone: "/registerDone",
  login: "/login",
  loginData: "/loginData",
  loginDone: "/loginDone",
  forgotPassword: "/forgotPassword",
};
