export * from "./login";
export * from "./loginData";
export * from "./loginOrRegister";
export * from "./onboarding1";
export * from "./onboarding2";
export * from "./register";
export * from "./registerData";
export * from "./registerDone";
export * from "./splashScreen";
